KSABooks/urls.py
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('ksa_books_app.urls'))
]

urlpatterns += staticfiles_urlpatterns()

ksa_books_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('', RedirectView.as_view(url='home/')),
    path('home/', views.home_view, name='home'),
    path('about/', views.about_view, name='about'),
    path('book-list/', views.BookListView.as_view(), name='book-list'),
    path('sell/', views.offer_create, name='sell'),
    path('search/', views.search_view, name='search'),
    path('offer/<int:pk>', views.offer_view, name='check-offer'),
    path('offer/<int:pk>/update', views.OfferUpdate.as_view(), name='update-offer'),
    path('offer/<int:pk>/delete', views.OfferDelete.as_view(), name='delete-offer'),
    path('my-offers/', views.my_offers, name='my-offers'),
    path('past-transaction/', views.past_transaction, name='past-transaction'),
    path('notification/', views.notification, name='notification'),
    path('setting/', views.setting, name='setting'),
    path('load-data/', views.load_data, name='load-data'),
    path('change-name', views.name_update, name='change-name'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

ksa_books_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.conf import settings
from django.urls import reverse
from math import log, ceil


class Subject(models.Model):
    name = models.CharField(max_length=10, verbose_name='교과명')

    def __str__(self):
        return self.name


class Course(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.SET_NULL, verbose_name='교과', null=True)
    name = models.CharField(max_length=50, verbose_name='과목명')
    open = models.BooleanField(verbose_name='수강 가능')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100, verbose_name='제목')
    author = models.CharField(max_length=100, verbose_name='저자')
    courses = models.ManyToManyField(Course, verbose_name='과목')
    subject = models.ForeignKey(Subject, verbose_name='교과', on_delete=models.SET_NULL, null=True)
    publisher = models.CharField(max_length=100, verbose_name='출판사')
    isbn = models.CharField(max_length=13, verbose_name='ISBN',
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    # link = models.URLField(max_length=300, verbose_name='책 링크')
    list_price = models.PositiveIntegerField(verbose_name='정가', null=True, blank=True)
    group_price = models.PositiveIntegerField(verbose_name='공동구매 가격', null=True, blank=True)
    using = models.BooleanField(verbose_name='사용 여부')

    class Meta:
        permissions = (
            ('load_data', 'Can load data'),
        )
        ordering = ['subject']

    def __str__(self):
        return f'({self.subject}, {self.display_courses()}){self.title}'

    def display_courses(self):
        return ', '.join([str(c) for c in self.courses.all()])

    display_courses.short_description = '수업'


QUALITY = (
    ('a', '상'),
    ('b', '중'),
    ('c', '하'),
)


class Offer(models.Model):
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,
                               related_name='offer_seller')
    buyer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
                              related_name='offer_buyer')
    want_users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    seller_done = models.BooleanField(null=True, default=False)
    seller_done_time = models.DateTimeField(null=True)
    buyer_done = models.BooleanField(null=True, default=False)
    buyer_done_time = models.DateTimeField(null=True)
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True, verbose_name='책')
    price = models.PositiveIntegerField(verbose_name='판매 가격')
    quality = models.CharField(choices=QUALITY, max_length=1, verbose_name='보관 상태', null=True)
    explain = models.TextField(verbose_name='내용', null=True, blank=True)
    date_time = models.DateTimeField(auto_now_add=True, null=True)
    views = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='views')

    def get_absolute_url(self):
        return reverse('check-offer', args=[str(self.id)])


class Comment(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,
                               related_name='comment_sender')
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
                                 related_name='comment_receiver')
    secret = models.BooleanField(null=True)
    text = models.TextField(verbose_name='댓글')
    date_time = models.DateTimeField(null=True, auto_now_add=True)
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, null=True)
    is_deleted = models.BooleanField(default=False, null=True)

    class Meta:
        ordering = ['-date_time']

    def __str__(self):
        return self.text


notifications_list = ['Comment', 'New offer', 'Sold to user', 'Sold to other', 'New want', 'Buyer cancel',
                      'Seller cancel']
COMMENT, NEW_OFFER, SOLD_TO_USER, SOLD_TO_OTHER, NEW_WANT, BUYER_CANCEL, SELLER_CANCEL = \
    tuple([str(i) for i in range(len(notifications_list))])
NOTIFICATIONS = tuple([(str(i), notifications_list[i]) for i in range(len(notifications_list))])


class Notification(models.Model):
    type = models.CharField(choices=NOTIFICATIONS, max_length=ceil(log(len(NOTIFICATIONS)+1, 10)), null=True)
    date_time = models.DateTimeField(auto_now_add=True, null=True)

    data_offer1 = models.ForeignKey(Offer, on_delete=models.SET_NULL, null=True, blank=True)
    data_user1 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name='data_user1')

    def html_form(self):
        html = []
        TEXT, LINK = 'text', 'link'
        if self.type == COMMENT:
            html.append((TEXT, f'{self.data_user1}이(가) '))
            html.append((LINK, self.data_offer1.book.title, self.data_offer1.get_absolute_url()))
            html.append((TEXT, '에 댓글을 달았습니다.'))
        elif self.type == NEW_OFFER:
            html.append((TEXT, f'{self.data_user1}이(가) '))
            html.append((LINK, self.data_offer1.book.title, self.data_offer1.get_absolute_url()))
            html.append((TEXT, '을(를) 판매하고 있습니다.'))
        elif self.type == SOLD_TO_USER:
            html.append((TEXT, f'{self.data_user1}이(가) 사용자에게 '))
            html.append((LINK, self.data_offer1.book.title, self.data_offer1.get_absolute_url()))
            html.append((TEXT, '을(를) 판매했습니다.'))
        elif self.type == SOLD_TO_OTHER:
            html.append((TEXT, f'{self.data_user1}이(가) 다른 사람에게 '))
            html.append((LINK, self.data_offer1.book.title, self.data_offer1.get_absolute_url()))
            html.append((TEXT, '을(를) 판매했습니다.'))
        elif self.type == NEW_WANT:
            html.append((TEXT, f'{self.data_user1}이(가) '))
            html.append((LINK, self.data_offer1.book.title, self.data_offer1.get_absolute_url()))
            html.append((TEXT, '을(를) 구매 신청했습니다.'))
        elif self.type == BUYER_CANCEL:
            html.append((TEXT, f'{self.data_user1}이(가) '))
            html.append((LINK, self.data_offer1.book.title, self.data_offer1.get_absolute_url()))
            html.append((TEXT, ' 구매를 취소했습니다.'))
        elif self.type == SELLER_CANCEL:
            html.append((TEXT, f'{self.data_user1}이(가) '))
            html.append((LINK, self.data_offer1.book.title, self.data_offer1.get_absolute_url()))
            html.append((TEXT, ' 판매를 취소했습니다.'))
        html.append(self.date_time)
        return html


class StudentUserManager(BaseUserManager):
    def create_user(self, student_id, name, password):
        user = self.model(student_id=student_id, name=name)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, student_id, name, password):
        user = self.create_user(student_id, name, password)
        user.is_active = True
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user


class StudentUser(AbstractBaseUser, PermissionsMixin):
    objects = StudentUserManager()
    student_id = models.CharField(max_length=10, verbose_name='학번', help_text='00-000', unique=True)
    name = models.CharField(max_length=100, verbose_name='이름')
    email = models.EmailField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    notifications = models.ManyToManyField(Notification, blank=True)
    unread_notification = models.PositiveIntegerField(default=0)

    notify_books = models.ManyToManyField(Book, verbose_name='원하는 책', blank=True)
    notify_comment = models.BooleanField(default=True, verbose_name='자신에게 댓글을 썼을 때')
    notify_new_offer = models.BooleanField(default=True, verbose_name='원하는 책이 올라왔을 때')
    notify_sold_to_user = models.BooleanField(default=True, verbose_name='자신에게 책을 판매했을 때')
    notify_sold_to_other = models.BooleanField(default=True, verbose_name='구매 신청한 책이 다른 사람에게 판매되었을 때')
    notify_new_want = models.BooleanField(default=True, verbose_name='자신의 책을 누군가 구매 신청했을 때')

    USERNAME_FIELD = 'student_id'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return ' '.join([self.student_id, self.name])

    def is_international(self):
        return self.student_id[3] == '2'

ksa_books_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Offer, Book, StudentUser

QUALITY_STANDARD = (
    '거의 새 것 같음',
    '다소 낡았지만 사용에는 지장이 없음',
    '구겨지거나 찢어져서 사용에 지장이 있음',
)


class OfferForm(ModelForm):
    price = forms.IntegerField(
        widget=forms.NumberInput(attrs={'step': 1000}),
    )

    class Meta:
        model = Offer
        fields = ['book', 'price', 'quality', 'explain']
        help_texts = {
            'quality': '<br>상: {}<br>중: {}<br>하: {}'.format(QUALITY_STANDARD[0], QUALITY_STANDARD[1],
                                                            QUALITY_STANDARD[2]),
        }


class OfferUpdateForm(OfferForm):
    book = forms.ModelChoiceField(queryset=Book.objects.all(), disabled=True)


MIN_QUALITY = (
    ('abc', '하 이상'),
    ('ab', '중 이상'),
    ('a', '상 이상'),
)

NEW, CHEAP = tuple([str(i) for i in range(2)])
SORT = (
    (NEW, '최신순'),
    (CHEAP, '가격순'),
)

UNSOLD, UNEXCHANGED, ALL = tuple([str(i) for i in range(3)])
STATE = (
    (UNSOLD, '판매되지 않은 책만'),
    (UNEXCHANGED, '거래되지 않은 책만'),
    (ALL, '모두'),
)


class SearchForm(forms.Form):
    book = forms.ModelChoiceField(label='책', queryset=Book.objects.all(), required=False)
    min_quality = forms.ChoiceField(label='보관 상태', choices=MIN_QUALITY, required=False)
    sort = forms.ChoiceField(label='정렬', choices=SORT, required=False)
    state = forms.ChoiceField(label='상태', choices=STATE, required=False)


class CommentForm(forms.Form):
    secret = forms.BooleanField(label='비밀글', required=False)
    receiver = forms.CharField(label='받는 사람', disabled=True, required=False)
    text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': '카톡 사용을 권장'}), label='댓글 입력')


class NotificationSettingForm(forms.ModelForm):
    notify_books = forms.ModelMultipleChoiceField(
        queryset=Book.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label='원하는 책 선택',
        required=False
    )

    class Meta:
        model = StudentUser
        fields = ['notify_new_offer', 'notify_books', 'notify_comment', 'notify_sold_to_user', 'notify_sold_to_other',
                  'notify_new_want']


class ChangeNameForm(forms.ModelForm):
    class Meta:
        model = StudentUser
        fields = ['name']

ksa_books_app/templates/base_generic.html
{% load tags %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <style>
        table, th, td {
            border: 2px solid #000000;
            border-collapse: collapse;
            padding: 3px;
            text-align: center;
        }
        table {
            width: 1000px;
        }
        th {
            background-color: #e0e0ff;
        }
        td {
            background-color: #f0fff0;
        }
        p {
            word-break: keep-all;
        }
        .container {
            max-width: 1000px;
            margin: auto;
        }
        .navigation {
            overflow: hidden;
            background-color: #e0e0e0;
            border-bottom: 1px solid black;
        }
        .navigation a, .navigation span {
            float: left;
            display: block;
            text-align: center;
            padding: 6px;
            text-decoration: none;
            font-weight: bold;
            font-size: large;
        }
        .navigation a {
            color: darkblue;
        }
        .navigation span {
            color: black;
        }
        .navigation a:hover {
            background-color: gray;
            color: white;
        }
        .user {
            float: right;
        }
        h2 {
            color: saddlebrown;
        }
        li {
            margin: 5px;
        }
        form {
            background-color: #f0f0f0;
            padding: 5px;
            border: 1px solid black;
            margin: 5px 0;
            box-shadow: 0 0 5px gray;
            border-radius: 5px;
        }
        label {
            font-weight: bold;
        }
        input[type='submit'] {
            font-size: large;
        }
        .content a[href] {
            color: saddlebrown;
            text-decoration: none;
        }
        .content a[href]:hover {
            color: #ff8a26;
        }
        .content a[href][target] {
            text-decoration: underline;
        }
    </style>
    {% block style %}{% endblock %}
    <meta charset="UTF-8">
    <title>KSABooks</title>
</head>
<body>
    <div class="container">
        <div class="navigation">
            <div class="user">
                {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}">로그아웃</a>
                    <span>{{ user }}</span>
                    {% if user.is_international %}
                        <a href="{% url 'change-name' %}">Change Name</a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'login' %}">로그인</a>
                {% endif %}
            </div>
        </div>
        <div class="navigation">
            <span>KSABooks</span>
            <a href="{% url 'home' %}">시작</a>
            <a href="{% url 'about' %}">정보</a>
            <a href="{% url 'sell' %}">판매</a>
            <a href="{% url 'search' %}">검색</a>
            <a href="{% url 'my-offers' %}">내 거래</a>
            <a href="{% url 'past-transaction' %}">종료된 거래</a>
            <a href="{% url 'book-list' %}">교과서 목록</a>
            {% if user.unread_notification == 0 or not user.is_authenticated %}
                <a href="{% url 'notification' %}">알림</a>
            {% else %}
                <a href="{% url 'notification' %}">알림({{ user.unread_notification }})</a>
            {% endif %}
            <a href="{% url 'setting' %}">설정</a>
        </div>

        <div class="content">
            {% block content %}{% endblock %}
        </div>

        {% block pagination %}
            {% if is_paginated %}
                <div>
                    <span>
                        {% if page_obj.has_previous %}
                            <a href="?{% url_replace request 'page' page_obj.previous_page_number %}">이전</a>
                        {% endif %}
                        <span>
                            페이지 {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="?{% url_replace request 'page' page_obj.next_page_number %}">다음</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        {% endblock %}
    </div>
</body>
</html>

ksa_books_app/templates/book_list.html
{% extends 'base_generic.html' %}

{% block content %}
    <h2>교과서 목록</h2>
    {% if object_list %}
        <table>
            <thead>
                <tr>
                    <th>교과</th>
                    <th>과목</th>
                    <th>제목</th>
                    <th>저자</th>
                    <th>출판사</th>
                    <th>ISBN</th>
                    <th>정가</th>
                    <th>공동구매</th>
                </tr>
            </thead>
            <tbody>
                {% for book in object_list %}
                    {% if book.using %}
                        <tr>
                            <td>{{ book.subject }}</td>
                            <td>{{ book.display_courses }}</td>
                            <td>{{ book.title }}</td>
                            <td>{{ book.author }}</td>
                            <td>{{ book.publisher }}</td>
                            <td>{{ book.isbn }}</td>
                            <td>{{ book.list_price }}</td>
                            <td>{{ book.group_price }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no books registered.</p>
    {% endif %}
{% endblock %}

ksa_books_app/templates/home.html
{% extends 'base_generic.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <h2>시작</h2>
        <h3>교과서 판매</h3>
        <ol>
            <li><a href="{% url 'sell' %}" target="_blank">판매하기</a>를 클릭한다.</li>
            <li>책 정보를 입력하고 확인을 누른다.</li>
            <li><a href="{% url 'my-offers' %}" target="_blank">내 거래</a>에 들어가면 거래 페이지를 확인할 수 있다.
                (<a href="{% url 'search' %}" target="_blank">검색</a>에는 본인의 책은 나오지 않으니 주의)</li>
            <li>누군가 책을 구매 신청하면 알림이 온다(<a href="{% url 'setting' %}" target="_blank">설정</a>에서 변경 가능).</li>
            <li>구매자와 거래 약속을 잡는다.</li>
            <li>약속을 잡고 나면 거래 페이지에서 구매자를 선택한 뒤 '판매'를 누른다.</li>
            <li>거래를 마친 뒤 '거래 완료'를 누른다.</li>
            <li>만약 다시 확인하고 싶다면 <a href="{% url 'past-transaction' %}" target="_blank">종료된 거래</a>에서 확인할 수 있다.</li>
        </ol>
        <h3>교과서 구매</h3>
        <ol>
            <li><a href="{% url 'search' %}" target="_blank">검색</a>에 들어가서 원하는 책을 찾는다.</li>
            <li>페이지에 들어가서 정보를 확인한다.</li>
            <li>구매를 원하면 '구매 신청'을 누른다.(이미 구매자가 있다면 버튼이 없음)</li>
            <li>판매자와 거래 약속을 잡고, 판매자가 '판매'를 누르기를 기다린다.
                누르면 알림이 오고(<a href="{% url 'setting' %}" target="_blank">설정</a>에서 변경 가능), 구매자에 자신이 보인다.</li>
            <li>거래를 마친 뒤 '거래 완료'를 누른다.</li>
            <li>만약 다시 확인하고 싶다면 <a href="{% url 'past-transaction' %}" target="_blank">종료된 거래</a>에서 확인할 수 있다.</li>
        </ol>
    {% else %}
        <h2>계정 사용 방법</h2>
        <ol>
            <li>이 사이트에 이미 모든 학생의 계정이 생성되어 있어서 계정을 만들 필요는 없음.
                자신의 계정의 비밀번호를 원하는 것으로 바꾸면 그 계정을 사용할 수 있음.</li>
            <li><a href="{% url 'password_reset' %}" target="_blank">비밀번호 변경</a>에 들어간다.</li>
            <li>자신의 학교 이메일을 입력한다.</li>
            <li>ksabooks1@gmail.com에서 이메일이 오면 링크를 클릭한다.(안 오면 스팸함 반드시 확인)</li>
            <li>계정 비밀번호를 변경한다.</li>
            <li>학번과 새 비밀번호로 <a href="{% url 'login' %}" target="_blank">로그인</a>한다.</li>
        </ol>
    {% endif %}
{% endblock %}

ksa_books_app/templates/load_data.html
{% extends 'base_generic.html' %}

{% block content %}
    <p>Successfully loaded data</p>
{% endblock %}

ksa_books_app/templates/name_update.html
{% extends 'base_generic.html' %}

{% block content %}
    <p>Change your name:</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Change">
    </form>
    <p>Please do not change it to anything other than your real name.</p>
    <p>(This feature is only for international students)</p>
{% endblock %}

ksa_books_app/templates/name_update_denied.html
{% extends 'base_generic.html' %}

{% block content %}
    <p>이름 변경은 국제학생들을 위해 만들어진 기능입니다.
        서로 모르는 학생끼리도 누구인지 확실히 알 수 있도록 국내학생들은 이름을 변경하는 것을 제한했습니다.
        반드시 이름을 변경해야 한다면, 20-017 김병권에게 연락을 주세요.</p>
{% endblock %}

ksa_books_app/templates/offer_view.html
{% extends 'base_generic.html' %}

{% block style %}
    <style>
        .offer {
            display: block;
            border-radius: 5px;
            background-color: #e0e0e0;
            border: 1px solid black;
        }
        .left {
            float: left;
        }
        .right {
            float: right;
        }
        a, span {
            padding: 5px;
        }
    </style>
{% endblock %}

{% block content %}
    <br>
    <div class="offer">
        <div class="left">
            <span>{{ offer.book.title }}</span>
        </div>
        <div class="right">
            <span>판매: {{ offer.seller }}</span>
            <span>구매: {{ offer.buyer }}</span>
        </div>
        <br>
        <div class="left">
            <span>가격: {{ offer.price }}원</span>
            <span>보관 상태: {{ offer.get_quality_display }}</span>
        </div>
        <br><br>
        <span>{{ offer.explain }}</span>
        <br><br>
        <span>읽은 사람: {{ views }}명</span>
        <div class="right">
            <span>{{ offer.date_time }}</span>
        </div>
    </div>
    {% comment %}
    Seller
    No one wants to buy:
    Someone wants to buy, no buyer chosen: sell-to
    Buyer chosen, not traded: sell-cancel, sell-done
    Traded: sell-done-cancel
    {% endcomment %}
    {% if offer.seller == user %}
        {% if offer.buyer %}
            {% if offer.seller_done %}
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="sell-done-cancel" value="True">
                    <input type="submit" value="거래 완료 취소">
                </form>
            {% else %}
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="sell-cancel" value="True">
                    <input type="submit" value="판매 취소">
                </form>
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="sell-done" value="True">
                    <input type="submit" value="거래 완료">
                </form>
            {% endif %}
        {% elif want_users.exists %}
            <form method="post">
                {% csrf_token %}
                <label for="buyer">구매자:</label>
                <select name="sell-to" id="buyer">
                    {% for want_user in want_users %}
                        <option value="{{ want_user.id }}">{{ want_user }}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="판매">
            </form>
        {% else %}
            <p>구매를 원하는 사람이 없음</p>
        {% endif %}
        <a href="{% url 'update-offer' pk=offer.pk %}">수정</a>
        <a href="{% url 'delete-offer' pk=offer.pk %}">삭제</a>
    {% comment %}
    Buyer
    Before clicking buy: want
    Clicked buy, not buyer: want-cancel
    Buyer, not traded: want-cancel, buy-done
    Traded: buy-done-cancel
    {% endcomment %}
    {% else %}
        {% if user not in want_users %}
            {% if offer.seller_done %}
                <p>이미 종료된 거래입니다.</p>
            {% else %}
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="want" value="True">
                    <input type="submit" value="구매 신청">
                </form>
            {% endif %}
        {% elif offer.buyer != user %}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="want-cancel" value="True">
                <input type="submit" value="구매 취소">
            </form>
        {% elif not offer.buyer_done %}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="want-cancel" value="True">
                <input type="submit" value="구매 취소">
            </form>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="buy-done" value="True">
                <input type="submit" value="거래 완료">
            </form>
        {% else %}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="buy-done-cancel" value="True">
                <input type="submit" value="거래 완료 취소">
            </form>
        {% endif %}
    {% endif %}
    <br>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ comment_form.as_p }}
        </table>
        <input type="submit" value="댓글 달기">
    </form>
    <br>
    <table>
        <tbody>
            {% for comment in comment_list %}
                {% if not comment.secret or comment.sender == user or comment.receiver == user %}
                    <tr>
                        <td>
                            <p>
                                {{ comment.sender }}
                                {% if offer.seller == comment.sender and comment.receiver %}
                                    ->{{ comment.receiver }}
                                {% endif %}
                                {{ comment.date_time }}
                                {% if comment.secret %}
                                    (비밀글)
                                {% endif %}
                            </p>
                            <p>{{ comment.text }}</p>
                            {% if comment.sender == user %}
                                <form method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="delete_comment" value={{ comment.id }}>
                                    <input type="submit" value="삭제">
                                </form>
                            {% elif offer.seller == user %}
                                <form method="get">
                                    {% csrf_token %}
                                    <input type="hidden" name="receiver" value={{ comment.sender.student_id }}>
                                    <input type="submit" value="답글">
                                </form>
                            {% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

ksa_books_app/templates/search.html
{% extends 'base_generic.html' %}

{% block style %}
    <style>
        ul {
            padding: unset;
        }
        li {
            display: block;
            border-radius: 5px;
            background-color: #e0e0e0;
            border: 1px solid black;
        }
        .left {
            float: left;
        }
        .right {
            float: right;
        }
        a, span {
            padding: 3px;
        }
    </style>
{% endblock %}

{% block content %}
    <h2>검색</h2>
    <form method="get">
        {% csrf_token %}
        <table>
            {{ form.as_p }}
        </table>
        <input type="submit" value="검색">
    </form>
    {% if page_obj %}
        <ul>
            {% for object in page_obj %}
                <li>
                    <div class="left">
                        <a href={{ object.get_absolute_url }}>{{ object.book.title }}</a>
                    </div>
                    <div class="right">
                        <span>{{ object.seller }}</span>
                    </div>
                    <br>
                    <div class="left">
                        <span>가격: {{ object.price }}원</span>
                        <span>보관 상태: {{ object.get_quality_display }}</span>
                    </div>
                    <div class="right">
                        <span>{{ object.date_time }}</span>
                    </div>
                    <br>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no offers.</p>
    {% endif %}
{% endblock %}